---
- name: tag exercise
  hosts: all
  remote_user: raghav
  become: yes
  tasks:
    - name: for tag1
      copy:
        dest: /tmp/tag1.html
        content: "I am tag1 raghav"
      tags: tag1
      when: inventory_hostname == 'servera' or inventory_hostname == 'serverc'
    - name: for tag2
      copy:
       dest: /tmp/tag2.html
       content: "I am tag2 by raghav"
      tags: tag2
      when: inventory_hostname == 'serverb' or inventory_hostname == 'serverd'
