---
- name: print variables
  hosts: all
  remote_user: raghav
  become: yes
  vars:
     users:
         test1:
              1st_name: test
              last_name: one
              home_dir: /home/test1
         test2:
              1st_name: test
              last_name: two
              home_dir: /home/test2
  tasks:
      - name: print variables
        debug:
            msg: "{{ users.test1 }} {{ users.test2.last_name }}"

