---
- name: pkg verification
  hosts: prod
  remote_user: raghav
  become: yes
  tasks:
    - name: yum module verification
      yum:
        name:
          - httpd
          - php
          - mariadb-server
          - firewalld
        state: latest
    - name: Start and enable service
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - mariadb
    - name: Allow traffic for web
      firewalld:
        service: http
        state: enabled
        immediate: yes
        permanent: yes
    - name: create a home page using line in file
      lineinfile:
        path: /var/www/html/index.html
        line: Web site created by Raghav
        create: yes



